/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ContributorRouteRouteImport } from './routes/contributor/route'
import { Route as ClusterManagerRouteRouteImport } from './routes/cluster-manager/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContributorIndexRouteImport } from './routes/contributor/index'
import { Route as ClusterManagerIndexRouteImport } from './routes/cluster-manager/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ContributorWalletIndexRouteImport } from './routes/contributor/wallet.index'
import { Route as ContributorPayoutsIndexRouteImport } from './routes/contributor/payouts.index'
import { Route as ContributorKycIndexRouteImport } from './routes/contributor/kyc.index'
import { Route as ContributorGroupsIndexRouteImport } from './routes/contributor/groups.index'
import { Route as ContributorContributionsIndexRouteImport } from './routes/contributor/contributions.index'
import { Route as ContributorComplaintsIndexRouteImport } from './routes/contributor/complaints.index'
import { Route as ClusterManagerPayoutsIndexRouteImport } from './routes/cluster-manager/payouts.index'
import { Route as ClusterManagerMembersIndexRouteImport } from './routes/cluster-manager/members.index'
import { Route as ClusterManagerKycIndexRouteImport } from './routes/cluster-manager/kyc.index'
import { Route as ClusterManagerIssuesIndexRouteImport } from './routes/cluster-manager/issues.index'
import { Route as ClusterManagerGroupsIndexRouteImport } from './routes/cluster-manager/groups.index'
import { Route as ClusterManagerContributionsIndexRouteImport } from './routes/cluster-manager/contributions.index'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports.index'
import { Route as AdminPoliciesIndexRouteImport } from './routes/admin/policies.index'
import { Route as AdminPayoutsIndexRouteImport } from './routes/admin/payouts.index'
import { Route as AdminGroupsIndexRouteImport } from './routes/admin/groups.index'
import { Route as AdminContributorsIndexRouteImport } from './routes/admin/contributors.index'
import { Route as AdminContributionsIndexRouteImport } from './routes/admin/contributions.index'
import { Route as AdminComplaintsIndexRouteImport } from './routes/admin/complaints.index'
import { Route as AdminClusterManagersIndexRouteImport } from './routes/admin/cluster-managers.index'
import { Route as HomeAuthSignupRouteImport } from './routes/home/auth/signup'
import { Route as HomeAuthLoginRouteImport } from './routes/home/auth/login'
import { Route as AuthResetPasswordRequestRouteImport } from './routes/auth/reset-password/request'
import { Route as AuthResetPasswordConfirmRouteImport } from './routes/auth/reset-password/confirm'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorRouteRoute = ContributorRouteRouteImport.update({
  id: '/contributor',
  path: '/contributor',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterManagerRouteRoute = ClusterManagerRouteRouteImport.update({
  id: '/cluster-manager',
  path: '/cluster-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorIndexRoute = ContributorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContributorRouteRoute,
} as any)
const ClusterManagerIndexRoute = ClusterManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClusterManagerRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ContributorWalletIndexRoute = ContributorWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => ContributorRouteRoute,
} as any)
const ContributorPayoutsIndexRoute = ContributorPayoutsIndexRouteImport.update({
  id: '/payouts/',
  path: '/payouts/',
  getParentRoute: () => ContributorRouteRoute,
} as any)
const ContributorKycIndexRoute = ContributorKycIndexRouteImport.update({
  id: '/kyc/',
  path: '/kyc/',
  getParentRoute: () => ContributorRouteRoute,
} as any)
const ContributorGroupsIndexRoute = ContributorGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => ContributorRouteRoute,
} as any)
const ContributorContributionsIndexRoute =
  ContributorContributionsIndexRouteImport.update({
    id: '/contributions/',
    path: '/contributions/',
    getParentRoute: () => ContributorRouteRoute,
  } as any)
const ContributorComplaintsIndexRoute =
  ContributorComplaintsIndexRouteImport.update({
    id: '/complaints/',
    path: '/complaints/',
    getParentRoute: () => ContributorRouteRoute,
  } as any)
const ClusterManagerPayoutsIndexRoute =
  ClusterManagerPayoutsIndexRouteImport.update({
    id: '/payouts/',
    path: '/payouts/',
    getParentRoute: () => ClusterManagerRouteRoute,
  } as any)
const ClusterManagerMembersIndexRoute =
  ClusterManagerMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => ClusterManagerRouteRoute,
  } as any)
const ClusterManagerKycIndexRoute = ClusterManagerKycIndexRouteImport.update({
  id: '/kyc/',
  path: '/kyc/',
  getParentRoute: () => ClusterManagerRouteRoute,
} as any)
const ClusterManagerIssuesIndexRoute =
  ClusterManagerIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => ClusterManagerRouteRoute,
  } as any)
const ClusterManagerGroupsIndexRoute =
  ClusterManagerGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => ClusterManagerRouteRoute,
  } as any)
const ClusterManagerContributionsIndexRoute =
  ClusterManagerContributionsIndexRouteImport.update({
    id: '/contributions/',
    path: '/contributions/',
    getParentRoute: () => ClusterManagerRouteRoute,
  } as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPoliciesIndexRoute = AdminPoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPayoutsIndexRoute = AdminPayoutsIndexRouteImport.update({
  id: '/payouts/',
  path: '/payouts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGroupsIndexRoute = AdminGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContributorsIndexRoute = AdminContributorsIndexRouteImport.update({
  id: '/contributors/',
  path: '/contributors/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContributionsIndexRoute = AdminContributionsIndexRouteImport.update({
  id: '/contributions/',
  path: '/contributions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComplaintsIndexRoute = AdminComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClusterManagersIndexRoute =
  AdminClusterManagersIndexRouteImport.update({
    id: '/cluster-managers/',
    path: '/cluster-managers/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const HomeAuthSignupRoute = HomeAuthSignupRouteImport.update({
  id: '/home/auth/signup',
  path: '/home/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeAuthLoginRoute = HomeAuthLoginRouteImport.update({
  id: '/home/auth/login',
  path: '/home/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRequestRoute =
  AuthResetPasswordRequestRouteImport.update({
    id: '/auth/reset-password/request',
    path: '/auth/reset-password/request',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthResetPasswordConfirmRoute =
  AuthResetPasswordConfirmRouteImport.update({
    id: '/auth/reset-password/confirm',
    path: '/auth/reset-password/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/cluster-manager': typeof ClusterManagerRouteRouteWithChildren
  '/contributor': typeof ContributorRouteRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/': typeof AdminIndexRoute
  '/cluster-manager/': typeof ClusterManagerIndexRoute
  '/contributor/': typeof ContributorIndexRoute
  '/auth/reset-password/confirm': typeof AuthResetPasswordConfirmRoute
  '/auth/reset-password/request': typeof AuthResetPasswordRequestRoute
  '/home/auth/login': typeof HomeAuthLoginRoute
  '/home/auth/signup': typeof HomeAuthSignupRoute
  '/admin/cluster-managers/': typeof AdminClusterManagersIndexRoute
  '/admin/complaints/': typeof AdminComplaintsIndexRoute
  '/admin/contributions/': typeof AdminContributionsIndexRoute
  '/admin/contributors/': typeof AdminContributorsIndexRoute
  '/admin/groups/': typeof AdminGroupsIndexRoute
  '/admin/payouts/': typeof AdminPayoutsIndexRoute
  '/admin/policies/': typeof AdminPoliciesIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/cluster-manager/contributions/': typeof ClusterManagerContributionsIndexRoute
  '/cluster-manager/groups/': typeof ClusterManagerGroupsIndexRoute
  '/cluster-manager/issues/': typeof ClusterManagerIssuesIndexRoute
  '/cluster-manager/kyc/': typeof ClusterManagerKycIndexRoute
  '/cluster-manager/members/': typeof ClusterManagerMembersIndexRoute
  '/cluster-manager/payouts/': typeof ClusterManagerPayoutsIndexRoute
  '/contributor/complaints/': typeof ContributorComplaintsIndexRoute
  '/contributor/contributions/': typeof ContributorContributionsIndexRoute
  '/contributor/groups/': typeof ContributorGroupsIndexRoute
  '/contributor/kyc/': typeof ContributorKycIndexRoute
  '/contributor/payouts/': typeof ContributorPayoutsIndexRoute
  '/contributor/wallet/': typeof ContributorWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AdminIndexRoute
  '/cluster-manager': typeof ClusterManagerIndexRoute
  '/contributor': typeof ContributorIndexRoute
  '/auth/reset-password/confirm': typeof AuthResetPasswordConfirmRoute
  '/auth/reset-password/request': typeof AuthResetPasswordRequestRoute
  '/home/auth/login': typeof HomeAuthLoginRoute
  '/home/auth/signup': typeof HomeAuthSignupRoute
  '/admin/cluster-managers': typeof AdminClusterManagersIndexRoute
  '/admin/complaints': typeof AdminComplaintsIndexRoute
  '/admin/contributions': typeof AdminContributionsIndexRoute
  '/admin/contributors': typeof AdminContributorsIndexRoute
  '/admin/groups': typeof AdminGroupsIndexRoute
  '/admin/payouts': typeof AdminPayoutsIndexRoute
  '/admin/policies': typeof AdminPoliciesIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/cluster-manager/contributions': typeof ClusterManagerContributionsIndexRoute
  '/cluster-manager/groups': typeof ClusterManagerGroupsIndexRoute
  '/cluster-manager/issues': typeof ClusterManagerIssuesIndexRoute
  '/cluster-manager/kyc': typeof ClusterManagerKycIndexRoute
  '/cluster-manager/members': typeof ClusterManagerMembersIndexRoute
  '/cluster-manager/payouts': typeof ClusterManagerPayoutsIndexRoute
  '/contributor/complaints': typeof ContributorComplaintsIndexRoute
  '/contributor/contributions': typeof ContributorContributionsIndexRoute
  '/contributor/groups': typeof ContributorGroupsIndexRoute
  '/contributor/kyc': typeof ContributorKycIndexRoute
  '/contributor/payouts': typeof ContributorPayoutsIndexRoute
  '/contributor/wallet': typeof ContributorWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/cluster-manager': typeof ClusterManagerRouteRouteWithChildren
  '/contributor': typeof ContributorRouteRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/': typeof AdminIndexRoute
  '/cluster-manager/': typeof ClusterManagerIndexRoute
  '/contributor/': typeof ContributorIndexRoute
  '/auth/reset-password/confirm': typeof AuthResetPasswordConfirmRoute
  '/auth/reset-password/request': typeof AuthResetPasswordRequestRoute
  '/home/auth/login': typeof HomeAuthLoginRoute
  '/home/auth/signup': typeof HomeAuthSignupRoute
  '/admin/cluster-managers/': typeof AdminClusterManagersIndexRoute
  '/admin/complaints/': typeof AdminComplaintsIndexRoute
  '/admin/contributions/': typeof AdminContributionsIndexRoute
  '/admin/contributors/': typeof AdminContributorsIndexRoute
  '/admin/groups/': typeof AdminGroupsIndexRoute
  '/admin/payouts/': typeof AdminPayoutsIndexRoute
  '/admin/policies/': typeof AdminPoliciesIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/cluster-manager/contributions/': typeof ClusterManagerContributionsIndexRoute
  '/cluster-manager/groups/': typeof ClusterManagerGroupsIndexRoute
  '/cluster-manager/issues/': typeof ClusterManagerIssuesIndexRoute
  '/cluster-manager/kyc/': typeof ClusterManagerKycIndexRoute
  '/cluster-manager/members/': typeof ClusterManagerMembersIndexRoute
  '/cluster-manager/payouts/': typeof ClusterManagerPayoutsIndexRoute
  '/contributor/complaints/': typeof ContributorComplaintsIndexRoute
  '/contributor/contributions/': typeof ContributorContributionsIndexRoute
  '/contributor/groups/': typeof ContributorGroupsIndexRoute
  '/contributor/kyc/': typeof ContributorKycIndexRoute
  '/contributor/payouts/': typeof ContributorPayoutsIndexRoute
  '/contributor/wallet/': typeof ContributorWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cluster-manager'
    | '/contributor'
    | '/verify-email'
    | '/admin/'
    | '/cluster-manager/'
    | '/contributor/'
    | '/auth/reset-password/confirm'
    | '/auth/reset-password/request'
    | '/home/auth/login'
    | '/home/auth/signup'
    | '/admin/cluster-managers/'
    | '/admin/complaints/'
    | '/admin/contributions/'
    | '/admin/contributors/'
    | '/admin/groups/'
    | '/admin/payouts/'
    | '/admin/policies/'
    | '/admin/reports/'
    | '/cluster-manager/contributions/'
    | '/cluster-manager/groups/'
    | '/cluster-manager/issues/'
    | '/cluster-manager/kyc/'
    | '/cluster-manager/members/'
    | '/cluster-manager/payouts/'
    | '/contributor/complaints/'
    | '/contributor/contributions/'
    | '/contributor/groups/'
    | '/contributor/kyc/'
    | '/contributor/payouts/'
    | '/contributor/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/verify-email'
    | '/admin'
    | '/cluster-manager'
    | '/contributor'
    | '/auth/reset-password/confirm'
    | '/auth/reset-password/request'
    | '/home/auth/login'
    | '/home/auth/signup'
    | '/admin/cluster-managers'
    | '/admin/complaints'
    | '/admin/contributions'
    | '/admin/contributors'
    | '/admin/groups'
    | '/admin/payouts'
    | '/admin/policies'
    | '/admin/reports'
    | '/cluster-manager/contributions'
    | '/cluster-manager/groups'
    | '/cluster-manager/issues'
    | '/cluster-manager/kyc'
    | '/cluster-manager/members'
    | '/cluster-manager/payouts'
    | '/contributor/complaints'
    | '/contributor/contributions'
    | '/contributor/groups'
    | '/contributor/kyc'
    | '/contributor/payouts'
    | '/contributor/wallet'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cluster-manager'
    | '/contributor'
    | '/verify-email'
    | '/admin/'
    | '/cluster-manager/'
    | '/contributor/'
    | '/auth/reset-password/confirm'
    | '/auth/reset-password/request'
    | '/home/auth/login'
    | '/home/auth/signup'
    | '/admin/cluster-managers/'
    | '/admin/complaints/'
    | '/admin/contributions/'
    | '/admin/contributors/'
    | '/admin/groups/'
    | '/admin/payouts/'
    | '/admin/policies/'
    | '/admin/reports/'
    | '/cluster-manager/contributions/'
    | '/cluster-manager/groups/'
    | '/cluster-manager/issues/'
    | '/cluster-manager/kyc/'
    | '/cluster-manager/members/'
    | '/cluster-manager/payouts/'
    | '/contributor/complaints/'
    | '/contributor/contributions/'
    | '/contributor/groups/'
    | '/contributor/kyc/'
    | '/contributor/payouts/'
    | '/contributor/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ClusterManagerRouteRoute: typeof ClusterManagerRouteRouteWithChildren
  ContributorRouteRoute: typeof ContributorRouteRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthResetPasswordConfirmRoute: typeof AuthResetPasswordConfirmRoute
  AuthResetPasswordRequestRoute: typeof AuthResetPasswordRequestRoute
  HomeAuthLoginRoute: typeof HomeAuthLoginRoute
  HomeAuthSignupRoute: typeof HomeAuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributor': {
      id: '/contributor'
      path: '/contributor'
      fullPath: '/contributor'
      preLoaderRoute: typeof ContributorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster-manager': {
      id: '/cluster-manager'
      path: '/cluster-manager'
      fullPath: '/cluster-manager'
      preLoaderRoute: typeof ClusterManagerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributor/': {
      id: '/contributor/'
      path: '/'
      fullPath: '/contributor/'
      preLoaderRoute: typeof ContributorIndexRouteImport
      parentRoute: typeof ContributorRouteRoute
    }
    '/cluster-manager/': {
      id: '/cluster-manager/'
      path: '/'
      fullPath: '/cluster-manager/'
      preLoaderRoute: typeof ClusterManagerIndexRouteImport
      parentRoute: typeof ClusterManagerRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/contributor/wallet/': {
      id: '/contributor/wallet/'
      path: '/wallet'
      fullPath: '/contributor/wallet/'
      preLoaderRoute: typeof ContributorWalletIndexRouteImport
      parentRoute: typeof ContributorRouteRoute
    }
    '/contributor/payouts/': {
      id: '/contributor/payouts/'
      path: '/payouts'
      fullPath: '/contributor/payouts/'
      preLoaderRoute: typeof ContributorPayoutsIndexRouteImport
      parentRoute: typeof ContributorRouteRoute
    }
    '/contributor/kyc/': {
      id: '/contributor/kyc/'
      path: '/kyc'
      fullPath: '/contributor/kyc/'
      preLoaderRoute: typeof ContributorKycIndexRouteImport
      parentRoute: typeof ContributorRouteRoute
    }
    '/contributor/groups/': {
      id: '/contributor/groups/'
      path: '/groups'
      fullPath: '/contributor/groups/'
      preLoaderRoute: typeof ContributorGroupsIndexRouteImport
      parentRoute: typeof ContributorRouteRoute
    }
    '/contributor/contributions/': {
      id: '/contributor/contributions/'
      path: '/contributions'
      fullPath: '/contributor/contributions/'
      preLoaderRoute: typeof ContributorContributionsIndexRouteImport
      parentRoute: typeof ContributorRouteRoute
    }
    '/contributor/complaints/': {
      id: '/contributor/complaints/'
      path: '/complaints'
      fullPath: '/contributor/complaints/'
      preLoaderRoute: typeof ContributorComplaintsIndexRouteImport
      parentRoute: typeof ContributorRouteRoute
    }
    '/cluster-manager/payouts/': {
      id: '/cluster-manager/payouts/'
      path: '/payouts'
      fullPath: '/cluster-manager/payouts/'
      preLoaderRoute: typeof ClusterManagerPayoutsIndexRouteImport
      parentRoute: typeof ClusterManagerRouteRoute
    }
    '/cluster-manager/members/': {
      id: '/cluster-manager/members/'
      path: '/members'
      fullPath: '/cluster-manager/members/'
      preLoaderRoute: typeof ClusterManagerMembersIndexRouteImport
      parentRoute: typeof ClusterManagerRouteRoute
    }
    '/cluster-manager/kyc/': {
      id: '/cluster-manager/kyc/'
      path: '/kyc'
      fullPath: '/cluster-manager/kyc/'
      preLoaderRoute: typeof ClusterManagerKycIndexRouteImport
      parentRoute: typeof ClusterManagerRouteRoute
    }
    '/cluster-manager/issues/': {
      id: '/cluster-manager/issues/'
      path: '/issues'
      fullPath: '/cluster-manager/issues/'
      preLoaderRoute: typeof ClusterManagerIssuesIndexRouteImport
      parentRoute: typeof ClusterManagerRouteRoute
    }
    '/cluster-manager/groups/': {
      id: '/cluster-manager/groups/'
      path: '/groups'
      fullPath: '/cluster-manager/groups/'
      preLoaderRoute: typeof ClusterManagerGroupsIndexRouteImport
      parentRoute: typeof ClusterManagerRouteRoute
    }
    '/cluster-manager/contributions/': {
      id: '/cluster-manager/contributions/'
      path: '/contributions'
      fullPath: '/cluster-manager/contributions/'
      preLoaderRoute: typeof ClusterManagerContributionsIndexRouteImport
      parentRoute: typeof ClusterManagerRouteRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/policies/': {
      id: '/admin/policies/'
      path: '/policies'
      fullPath: '/admin/policies/'
      preLoaderRoute: typeof AdminPoliciesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payouts/': {
      id: '/admin/payouts/'
      path: '/payouts'
      fullPath: '/admin/payouts/'
      preLoaderRoute: typeof AdminPayoutsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/groups/': {
      id: '/admin/groups/'
      path: '/groups'
      fullPath: '/admin/groups/'
      preLoaderRoute: typeof AdminGroupsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contributors/': {
      id: '/admin/contributors/'
      path: '/contributors'
      fullPath: '/admin/contributors/'
      preLoaderRoute: typeof AdminContributorsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contributions/': {
      id: '/admin/contributions/'
      path: '/contributions'
      fullPath: '/admin/contributions/'
      preLoaderRoute: typeof AdminContributionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/complaints/': {
      id: '/admin/complaints/'
      path: '/complaints'
      fullPath: '/admin/complaints/'
      preLoaderRoute: typeof AdminComplaintsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cluster-managers/': {
      id: '/admin/cluster-managers/'
      path: '/cluster-managers'
      fullPath: '/admin/cluster-managers/'
      preLoaderRoute: typeof AdminClusterManagersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/home/auth/signup': {
      id: '/home/auth/signup'
      path: '/home/auth/signup'
      fullPath: '/home/auth/signup'
      preLoaderRoute: typeof HomeAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/auth/login': {
      id: '/home/auth/login'
      path: '/home/auth/login'
      fullPath: '/home/auth/login'
      preLoaderRoute: typeof HomeAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/request': {
      id: '/auth/reset-password/request'
      path: '/auth/reset-password/request'
      fullPath: '/auth/reset-password/request'
      preLoaderRoute: typeof AuthResetPasswordRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/confirm': {
      id: '/auth/reset-password/confirm'
      path: '/auth/reset-password/confirm'
      fullPath: '/auth/reset-password/confirm'
      preLoaderRoute: typeof AuthResetPasswordConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClusterManagersIndexRoute: typeof AdminClusterManagersIndexRoute
  AdminComplaintsIndexRoute: typeof AdminComplaintsIndexRoute
  AdminContributionsIndexRoute: typeof AdminContributionsIndexRoute
  AdminContributorsIndexRoute: typeof AdminContributorsIndexRoute
  AdminGroupsIndexRoute: typeof AdminGroupsIndexRoute
  AdminPayoutsIndexRoute: typeof AdminPayoutsIndexRoute
  AdminPoliciesIndexRoute: typeof AdminPoliciesIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminClusterManagersIndexRoute: AdminClusterManagersIndexRoute,
  AdminComplaintsIndexRoute: AdminComplaintsIndexRoute,
  AdminContributionsIndexRoute: AdminContributionsIndexRoute,
  AdminContributorsIndexRoute: AdminContributorsIndexRoute,
  AdminGroupsIndexRoute: AdminGroupsIndexRoute,
  AdminPayoutsIndexRoute: AdminPayoutsIndexRoute,
  AdminPoliciesIndexRoute: AdminPoliciesIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ClusterManagerRouteRouteChildren {
  ClusterManagerIndexRoute: typeof ClusterManagerIndexRoute
  ClusterManagerContributionsIndexRoute: typeof ClusterManagerContributionsIndexRoute
  ClusterManagerGroupsIndexRoute: typeof ClusterManagerGroupsIndexRoute
  ClusterManagerIssuesIndexRoute: typeof ClusterManagerIssuesIndexRoute
  ClusterManagerKycIndexRoute: typeof ClusterManagerKycIndexRoute
  ClusterManagerMembersIndexRoute: typeof ClusterManagerMembersIndexRoute
  ClusterManagerPayoutsIndexRoute: typeof ClusterManagerPayoutsIndexRoute
}

const ClusterManagerRouteRouteChildren: ClusterManagerRouteRouteChildren = {
  ClusterManagerIndexRoute: ClusterManagerIndexRoute,
  ClusterManagerContributionsIndexRoute: ClusterManagerContributionsIndexRoute,
  ClusterManagerGroupsIndexRoute: ClusterManagerGroupsIndexRoute,
  ClusterManagerIssuesIndexRoute: ClusterManagerIssuesIndexRoute,
  ClusterManagerKycIndexRoute: ClusterManagerKycIndexRoute,
  ClusterManagerMembersIndexRoute: ClusterManagerMembersIndexRoute,
  ClusterManagerPayoutsIndexRoute: ClusterManagerPayoutsIndexRoute,
}

const ClusterManagerRouteRouteWithChildren =
  ClusterManagerRouteRoute._addFileChildren(ClusterManagerRouteRouteChildren)

interface ContributorRouteRouteChildren {
  ContributorIndexRoute: typeof ContributorIndexRoute
  ContributorComplaintsIndexRoute: typeof ContributorComplaintsIndexRoute
  ContributorContributionsIndexRoute: typeof ContributorContributionsIndexRoute
  ContributorGroupsIndexRoute: typeof ContributorGroupsIndexRoute
  ContributorKycIndexRoute: typeof ContributorKycIndexRoute
  ContributorPayoutsIndexRoute: typeof ContributorPayoutsIndexRoute
  ContributorWalletIndexRoute: typeof ContributorWalletIndexRoute
}

const ContributorRouteRouteChildren: ContributorRouteRouteChildren = {
  ContributorIndexRoute: ContributorIndexRoute,
  ContributorComplaintsIndexRoute: ContributorComplaintsIndexRoute,
  ContributorContributionsIndexRoute: ContributorContributionsIndexRoute,
  ContributorGroupsIndexRoute: ContributorGroupsIndexRoute,
  ContributorKycIndexRoute: ContributorKycIndexRoute,
  ContributorPayoutsIndexRoute: ContributorPayoutsIndexRoute,
  ContributorWalletIndexRoute: ContributorWalletIndexRoute,
}

const ContributorRouteRouteWithChildren =
  ContributorRouteRoute._addFileChildren(ContributorRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ClusterManagerRouteRoute: ClusterManagerRouteRouteWithChildren,
  ContributorRouteRoute: ContributorRouteRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthResetPasswordConfirmRoute: AuthResetPasswordConfirmRoute,
  AuthResetPasswordRequestRoute: AuthResetPasswordRequestRoute,
  HomeAuthLoginRoute: HomeAuthLoginRoute,
  HomeAuthSignupRoute: HomeAuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
